# **Python for Data Analysis - Pandas, Numpy and Basic Python.**

### Guidelines for the test:
1. The test time duration is 2 hours.
2. For theory questions add a markdown cell below the question and answer the questions.
3. For coding questions add the cells as needed and write the code.
4. Make sure the answer is descriptive and contains correct examples as needed.
5. After completion of test, upload the test notebook to your github profile and share the link.
6. **Do not use any other resources like google, chatgpt, copilot, gemini, deepseeks etc..**

**Q1. Define a Series and a DataFrame in Pandas. Create a Dataframe from Series and dataframe from dictionarry.**

* series is one dimensional array that is capable to hold data of any type
* syntax: pd.Series()
* dataframe is kind of excel in which 2d array can be store in different columns
* syntax : pd.DataFrame()

In [19]:
import pandas as pd 

name = pd.Series(["raksh","neha","sneha"])
age = pd.Series([23,22,21])

a= pd.DataFrame({"name":name,
                 "age":age})
print(a)

    name  age
0  raksh   23
1   neha   22
2  sneha   21


In [31]:
data = {"name" : ["raksh","neha","sneha"],
        "age" : [23,22,21],
        "city" : ["bpq","hyd","pune"]}

b = pd.DataFrame(data)
print(b)

    name  age  city
0  raksh   23   bpq
1   neha   22   hyd
2  sneha   21  pune


**Q2. Explain the use of groupby() in Pandas with a simple use case.**

It is used to split data in groups based on some condition 
syntax : groupby()


In [39]:
data = {
    "Class": ["A", "A", "B", "B", "B", "C"],
    "Student": ["Ram", "Shyam", "Radha", "Geeta", "Mohan", "Sita"]
}

df = pd.DataFrame(data)
print(df)

count = df.groupby("Class")["Student"].count()
print(count)

  Class Student
0     A     Ram
1     A   Shyam
2     B   Radha
3     B   Geeta
4     B   Mohan
5     C    Sita
Class
A    2
B    3
C    1
Name: Student, dtype: int64


**Q3.What is the difference between merging and concatenating DataFrames in Pandas? Explain it using an example.**

merging : combining two dataframe based on one common column
syntax: pd.merge()
concatenating : it just like adding a additional data into frame 
syntax : pd.concat()


In [51]:
#merge
print("the merged data is")
a = pd.DataFrame({ "id" : [1,2,3],
                  "name" : ["raksh","neha","sneha"]})
b = pd.DataFrame({ "id" : [1,2,3],
                  "age" : [23,22,21]})

c = pd.merge(a,b , on="id")
print(c)


#concat
print("the concatenated data is ")
a = pd.DataFrame({ "id" : [1,2,3],
                  "name" : ["raksh","neha","sneha"]})
b = pd.DataFrame({ "id" : [1,2,3],
                  "age" : [23,22,21]})

c = pd.concat([a,b])
print(c)
              

the merged data is
   id   name  age
0   1  raksh   23
1   2   neha   22
2   3  sneha   21
the concatenated data is 
   id   name   age
0   1  raksh   NaN
1   2   neha   NaN
2   3  sneha   NaN
0   1    NaN  23.0
1   2    NaN  22.0
2   3    NaN  21.0


**Q4. Create a random 10x10 array of numbers between 0 and 100. Then:**

- **Replace all values greater than 50 with 50.**
- **Calculate the mean of all values between 20 and 40.**
- **Extract all even numbers from the array.**

In [67]:
import numpy as np
arr = np.random.randint(0,101,(10,10))
print(arr)
arr[arr>50]=50
print(arr)
d= (arr>=20)&(arr<=40)
print("mean of values",d.mean())
e = arr[arr%2 == 0]
print(e)

[[ 3 60 74 13 59 35 80 23 90  3]
 [13 90 30 54  3 22 41 66 70 71]
 [27 22 82 51 54 59 72 71  0 31]
 [86 73  8 73 90 73  3 66 87 66]
 [31 72 65 25 60 36 34 45 17 50]
 [89 96 89 60  7 30 81 32 93 49]
 [89 20 14 10 23  5 35  3 35 71]
 [75 95 84  7 50 95 27 43 91 99]
 [ 8 49 55 72 42 10 72  5 42 22]
 [89 28 15 16 53 32 54 49 95 96]]
[[ 3 50 50 13 50 35 50 23 50  3]
 [13 50 30 50  3 22 41 50 50 50]
 [27 22 50 50 50 50 50 50  0 31]
 [50 50  8 50 50 50  3 50 50 50]
 [31 50 50 25 50 36 34 45 17 50]
 [50 50 50 50  7 30 50 32 50 49]
 [50 20 14 10 23  5 35  3 35 50]
 [50 50 50  7 50 50 27 43 50 50]
 [ 8 49 50 50 42 10 50  5 42 22]
 [50 28 15 16 50 32 50 49 50 50]]
mean of values 0.21
[50 50 50 50 50 50 30 50 22 50 50 50 22 50 50 50 50 50 50  0 50 50  8 50
 50 50 50 50 50 50 50 50 36 34 50 50 50 50 50 30 50 32 50 50 20 14 10 50
 50 50 50 50 50 50 50  8 50 50 42 10 50 42 22 50 28 16 50 32 50 50 50]


**Q5.Create a dataframe in Pandas, add columns such as product name, product id,product price, product sale, product quantity, product discount, region sold.Add atleast 10 records and Display the following using Pandas:**

- **The top 5 rows of the dataset**

- **Number of unique products sold**

- **Total revenue for each region (Revenue = Quantity × Price × (1 - Discount))**
- **Create a pivot table showing total Quantity sold per Region and Product.**



In [71]:
import pandas as pd

data = {
    "Product Name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Charger",
                     "Laptop", "Keyboard", "Mouse", "Monitor", "Charger"],
    "Product ID": [201, 202, 203, 204, 205, 201, 203, 202, 204, 205],
    "Price": [50000, 800, 1500, 12000, 1000, 48000, 1400, 850, 11000, 950],
    "Sale": [True, True, True, False, True, True, True, True, False, True],
    "Quantity": [5, 30, 20, 10, 25, 3, 15, 35, 7, 20],
    "Discount": [0.1, 0.05, 0.1, 0.2, 0, 0.1, 0.05, 0.05, 0.2, 0],
    "Region": ["West", "North", "South", "East", "South",
               "North", "East", "West", "South", "North"]
}

df = pd.DataFrame(data)
print (df)

  Product Name  Product ID  Price   Sale  Quantity  Discount Region
0       Laptop         201  50000   True         5      0.10   West
1        Mouse         202    800   True        30      0.05  North
2     Keyboard         203   1500   True        20      0.10  South
3      Monitor         204  12000  False        10      0.20   East
4      Charger         205   1000   True        25      0.00  South
5       Laptop         201  48000   True         3      0.10  North
6     Keyboard         203   1400   True        15      0.05   East
7        Mouse         202    850   True        35      0.05   West
8      Monitor         204  11000  False         7      0.20  South
9      Charger         205    950   True        20      0.00  North


In [73]:
df.head()

Product Name  Product ID  Price   Sale  Quantity  Discount Region
0       Laptop         201  50000   True         5      0.10   West
1        Mouse         202    800   True        30      0.05  North
2     Keyboard         203   1500   True        20      0.10  South
3      Monitor         204  12000  False        10      0.20   East
4      Charger         205   1000   True        25      0.00  South

In [77]:
df.nunique()

Product Name     5
Product ID       5
Price           10
Sale             2
Quantity         9
Discount         4
Region           4
dtype: int64

In [97]:
df["Revenue"] = df["Quantity"] * df["Price"] * (1 - df["Discount"])
total = df.groupby("Region")["Revenue"].sum()
print( total)

Region
East     115950.0
North    171400.0
South    113600.0
West     253262.5
Name: Revenue, dtype: float64


**Q6. Using the following sales data:**

```
sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=10),
    'Product': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Revenue': [100, 150, 120, 80, 160, 110, 90, 170, 130, 85]
})
```
- **Calculate the total revenue per product**

- **Find the date with the highest revenue**



In [111]:
sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=10),
    'Product': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Revenue': [100, 150, 120, 80, 160, 110, 90, 170, 130, 85]
})

print(sales)

total = sales.groupby("Product")["Revenue"].sum()
print(total)

        Date Product  Revenue
0 2023-01-01       A      100
1 2023-01-02       B      150
2 2023-01-03       A      120
3 2023-01-04       C       80
4 2023-01-05       B      160
5 2023-01-06       A      110
6 2023-01-07       C       90
7 2023-01-08       B      170
8 2023-01-09       A      130
9 2023-01-10       C       85
Product
A    460
B    480
C    255
Name: Revenue, dtype: int64


**Q7.When would you use np.random.choice() vs np.random.randint()? Explain with example.**



In [117]:
 #np.random.choice() = it is used when we want to randomly pick array , with repeated elements 
#syntax : np.random.choice()
f = [11,15,16,16, 17 ,18]
g =  np.random.choice(f)
print(g)

18


In [121]:
#np.random.randint() : it is used when we want to create an array from a specific range of number and also size of an array can be given 
#syntax = np.random.randint()

g =  np.random.randint(10,99, (3,3))
print(g)


[[86 15 12]
 [54 83 33]
 [77 13 72]]


**Q8.Create a 1D NumPy array of 100 random integers from 1 to 500.**

- **Filter values that are divisible by 5 and greater than 250.**

- **Calculate the mean, median, standard deviation of the filtered array**

In [125]:
arr = np.random.randint(1, 501, size=100)
print(arr)

filtered = arr[(arr % 5 == 0) & (arr > 250)]
print(filtered)

print("mean",np.mean(filtered))
print("median",np.median(filtered))
print("standard deviation",np.std(filtered))

[209 385   1 276  70 255 450 373  27  67 447  12 106 343 118 488 242 407
 153 457 146 341  33 249 183  28 203  64 456  40 202 220 117 433 133 264
  71 294 363 171 243 100 446 160 493 237 374  37 163 446 120 454 240 235
 360 209 215 310 374  72 461 357 453 231  22  31 456 461 111 157 461 157
 232 296 398 164 212 333  28 327 483 115 223  77 109  36 159 417  99 150
 193 259 286 189  51 466 157  89 302 430]
[385 255 450 360 310 430]
mean 365.0
median 372.5
standard deviation 67.08203932499369


**Q9.How can you detect and remove duplicate rows in a DataFrame? Explain with an example.**



In [135]:
#we can detect the duplicates by using .duplicate()  and remove them by using .drop_duplicate() 

df = pd.DataFrame({
    'Name': ['ab', 'cd', 'ef', 'gh'],
    'Age': [22, 25, 22, 30]
})

print("Original DataFrame:")
print(df)

i = df.drop_duplicates()
print("after duplicates is removed")
print(i)

Original DataFrame:
  Name  Age
0   ab   22
1   cd   25
2   ef   22
3   gh   30
after duplicates is removed
  Name  Age
0   ab   22
1   cd   25
2   ef   22
3   gh   30


**Q10.What is the purpose of the agg() function in Pandas? Provide two examples of its use.**



In [ ]:
agg() = aggregate funtion is used

**Q11. Describe three different ways to filter rows in a Pandas DataFrame.**


**Q12. Given:**

```
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 9, 8, 7, 6])
```

- **Create a 2D array where the first row is a and second row is b**

- **Swap the first and last columns of this new array**

- **Reverse the elements along the second axis**

In [139]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 9, 8, 7, 6])

arr = np.array([a, b])
print( arr)

rarr = arr[:, ::-1]
print( rarr)

[[ 1  2  3  4  5]
 [10  9  8  7  6]]
[[ 5  4  3  2  1]
 [ 6  7  8  9 10]]


**Q13. What is the difference between np.nan, None, and pd.NA in data handling?**

**Q14. What is the use of df.query() in Pandas? Explain with example.**


**Q15. What are the key differences between np.array() and pd.Series()?**



In [ ]:
np.array()= used for numerical operation to create an array 
pd.Series() = one-dimensional array used for data analysis.

**Q16. Assuming the dataset you've created in Q5, Filter all rows where:**
- **Discount is between 0.1 and 0.3 (inclusive)**

- **AND Region is not 'South'**

- **AND Revenue > 500**

In [145]:
j= pd.DataFrame({
    'Product': ['mob', 'cell', 'lappy', 'mouse', 'cpu'],
    'Discount': [0.05, 0.15, 0.25, 0.30, 0.20],
    'Region': ['North', 'South', 'East', 'West', 'South'],
    'Revenue': [400, 600, 700, 800, 550]
})

filtered = j[
    (j['Discount'] >= 0.1) &
    (j['Discount'] <= 0.3) &
    (j['Region'] != 'South') &
    (j['Revenue'] > 500)
]

print(filtered)

  Product  Discount Region  Revenue
2   lappy      0.25   East      700
3   mouse      0.30   West      800


**Q17. Create a dataset where you have customer purchase frequency and revenue columns along with sales, product, region, product price etc.. Add 25-30 records and:**

**Create 3 segments:**

- **High Value (high revenue & high frequency)**

- **Low Value (low revenue)**

- **Occasional (low frequency)**

- **Count customers in each segment**